#!/bin/bash

SSHFS=sshfs
KEYPATH=$HOME/mnt/keys
MOUNT="sshfs -o identityFile=${KEYPATH}/${USER}_desktop"
UNMOUNT="fusermount -u"
SL="-o follow_symlinks"

function notice {

    /bin/echo -e " \033[36m>>\033[0m $@"
}

function mount {

    $MOUNT $@ &> /dev/null
    
    if [ $? -eq 0 ]; then
        /bin/echo -e -n " [\033[32m**\033[0m] "
    else 
        /bin/echo -e -n " [\033[31m!!\033[0m] "
    fi
    
    /bin/echo -e "$1"
}

function unmount {
    
    $UNMOUNT $2 &> /dev/null
    
    if [ $? -eq 0 ]; then
        /bin/echo -e -n " [\033[32m**\033[0m] "
    else 
        /bin/echo -e -n " [\033[31m!!\033[0m] "
    fi
    
    /bin/echo -e "$2"
}

CMD="mount"
if [ $# -gt 0 ]; then
    if [ "$1" = "-u" ]; then
        if [ $# -gt 1 ] && [ "$2" = "-f" ]; then
            UNMOUNT="$UNMOUNT -z"
        fi
        CMD="unmount"
    fi
fi

#$CMD $HOST:$REMOTE_KEYPATH $KEYPATH &> /dev/null

#$CMD $HOST:$REMOTE_PATH $LOCAL_PATH

